import math
import warnings

import torch
import torch.nn as nn
from torch.nn import functional as F

from torch import Tensor
from einops import rearrange
from functools import reduce
from typing import Callable, Optional, Tuple

ndims = 3 # H,W,D


# these functions are adopted from timm.
def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor


class timm_DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob: float = 0., scale_by_keep: bool = True):
        super(timm_DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)

    def extra_repr(self):
        return f'drop_prob={round(self.drop_prob,3):0.3f}'


def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor



def timm_trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    NOTE: this impl is similar to the PyTorch trunc_normal_, the bounds [a, b] are
    applied while sampling the normal with mean/std applied, therefore a, b args
    should be adjusted to match the range of mean, std args.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)



class Conv3dReLU(nn.Sequential):
    def __init__(
            self,
            in_channels,
            out_channels,
            kernel_size,
            padding=0,
            stride=1,
            use_batchnorm=True,
    ):
        conv = nn.Conv3d(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=padding,
            bias=False,
        )
        relu = nn.LeakyReLU(inplace=True)
        if not use_batchnorm:
            nm = nn.InstanceNorm3d(out_channels)
        else:
            nm = nn.BatchNorm3d(out_channels)
        super(Conv3dReLU, self).__init__(conv, nm, relu)


def get_norm(name, **kwargs):
    if name.lower() == 'BatchNorm2d'.lower():
        BatchNorm = getattr(nn, 'BatchNorm%dd' % ndims)
        return BatchNorm(**kwargs)
    elif name.lower() == 'instance':
        InstanceNorm = getattr(nn, 'InstanceNorm%dd' % ndims)
        return InstanceNorm(**kwargs)
    elif name.lower() == 'None'.lower():
        return nn.Identity()
    else:
        return NotImplementedError


def get_activation(name, **kwargs):
    if name.lower() == 'ReLU'.lower():
        return nn.ReLU()
    elif name.lower() == 'GELU'.lower():
        return nn.GELU()
    elif name.lower() == 'None'.lower():
        return nn.Identity()
    else:
        return NotImplementedError

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def prod_func(Vec):
  return reduce( lambda x, y: x*y, Vec ) #  math.prod()

def downsampler_fn(img, out_size):
    """
    input sahep: B,C,H,W,D
    output sahep: B,C,H,W,D
    """
    return nn.functional.interpolate(img,
                                     size=out_size,
                                     mode='nearest',
                                     align_corners=None,
                                     recompute_scale_factor=None,
                                     #antialias=False
                                     )


def get_norm(name, **kwargs):
    if name.lower() == 'BatchNorm'.lower():
        BatchNorm = getattr(nn, 'BatchNorm%dd' % ndims)
        return BatchNorm(**kwargs)
    elif name.lower() in ['instance', 'InstanceNorm'.lower()]:
        InstanceNorm = getattr(nn, 'InstanceNorm%dd' % ndims)
        return InstanceNorm(**kwargs)
    elif name.lower() == 'None'.lower():
        return nn.Identity()
    else:
        return NotImplementedError


def get_activation(name, **kwargs):
    if name.lower() == 'ReLU'.lower():
        return nn.ReLU()
    elif name.lower() == 'GELU'.lower():
        return nn.GELU()
    elif name.lower() == 'None'.lower():
        return nn.Identity()
    else:
        return NotImplementedError



def downsampler_fn(data, out_size):
    """
    input sahep: B,Ci,Hi,Wi,Di
    output sahep: B,C,H,W,D

    """
    out = nn.functional.interpolate(data,
                                     size=out_size,
                                     mode='trilinear',
                                     align_corners=None,
                                     recompute_scale_factor=None,
                                     #antialias=False
    )
    return out.to(data.device)


class MLP(nn.Module):
    def __init__(self,
                in_feats,
                MLP_type="basic", # scmlp conv basic
                hid_feats=None,
                out_feats=None,
                kernel_size=3,
                act_name="GELU",
                drop=0.,
                bias=False,
            )->None:
        super(MLP, self).__init__()

        out_feats = out_feats or in_feats
        hid_feats = hid_feats or in_feats

        if MLP_type.lower()=="scmlp":
            # improved MLP : 3x3conv (spatial) -> eca (channel) -> mlp
            self.net = nn.Sequential(*[
                rearrange('B h w c -> B c h w'),
                nn.Conv3d(in_feats, out_feats, kernel_size=1, bias=bias),
                nn.BatchNorm3d(out_feats),
                get_activation(act_name),
                rearrange('B c h w d -> B h w d c'),
                nn.Linear(out_feats, out_feats),
                get_activation(act_name),
                nn.Dropout(drop),
                nn.Linear(out_feats, out_feats),
                get_activation(act_name),
                nn.Dropout(drop),
            ])


        elif MLP_type.lower()=="conv":
            # improved MLP # RVT cvpr2022
            self.net = nn.Sequential(*[
                rearrange('B h w c -> B c h w'),
                nn.Conv3d(in_feats, hid_feats, kernel_size=1, bias=bias),
                nn.BatchNorm2d(hid_feats),
                get_activation(act_name),
                nn.Dropout(drop),
                nn.Conv3d(hid_feats, hid_feats, kernel_size=kernel_size,
                    padding=int(kernel_size//2), groups=hid_feats, bias=bias),
                nn.BatchNorm2d(hid_feats),
                get_activation(act_name),
                nn.Conv3d(hid_feats, out_feats, kernel_size=1, bias=bias),
                nn.BatchNorm2d(out_feats),
                nn.Dropout(drop),
                rearrange('B c h w-> B h w c'),
            ])


        elif MLP_type.lower()=="basic":
            self.net = nn.Sequential(*[
                    nn.Linear(in_feats, hid_feats),
                    get_activation(act_name),
                    nn.Dropout(drop),
                    nn.Linear(hid_feats, out_feats),
                    nn.Dropout(drop)
            ])

    def forward(self, x)-> torch.Tensor:
        x = self.net(x)
        return x


class FiLMParameterGenerator(nn.Module):
    """
    Generate FiLM parameters (gamma, beta) from a conditioning feature map.

    The generator pools the conditioning tensor to a channel descriptor and
    predicts per-channel scale and shift values that are softly bounded for
    numerical stability.
    """

    def __init__(self, cond_dim: int, target_dim: int, reduction: int = 4):
        super().__init__()
        hidden_dim = max(cond_dim // reduction, 4)
        self.pool = nn.AdaptiveAvgPool3d(1)
        self.proj = nn.Sequential(
            nn.Conv3d(cond_dim, hidden_dim, kernel_size=1),
            nn.ReLU(inplace=True),
            nn.Conv3d(hidden_dim, target_dim * 2, kernel_size=1),
        )

    def forward(self, cond: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        x = self.pool(cond)
        params = self.proj(x).view(cond.size(0), 2, -1)
        gamma = torch.tanh(params[:, 0]) * 0.5 + 1.0
        beta = torch.tanh(params[:, 1]) * 0.5
        return gamma, beta


class SimpleMambaBlock(nn.Module):
    """
    Lightweight Mamba-inspired block for volumetric features.

    The block keeps the state-space intuition (depthwise convolutional mixing
    plus input/output projections) while remaining framework-agnostic. A FiLM
    tuple ``(gamma, beta)`` can be provided to modulate the normalized tokens
    for cross-conditioning.
    """

    def __init__(
        self,
        dim: int,
        state_expand: int = 2,
        d_conv: int = 3,
        dropout: float = 0.0,
        norm_layer: Callable[[int], nn.Module] = nn.LayerNorm,
    ):
        super().__init__()
        self.dim = dim
        inner_dim = dim * state_expand
        self.norm = norm_layer(dim)
        self.in_proj = nn.Linear(dim, inner_dim * 2)
        self.conv = nn.Conv1d(
            inner_dim,
            inner_dim,
            kernel_size=d_conv,
            padding=d_conv // 2,
            groups=inner_dim,
        )
        self.out_proj = nn.Linear(inner_dim, dim)
        self.act = nn.GELU()
        self.dropout = nn.Dropout(dropout)

    def forward(
        self, x: torch.Tensor, film: Optional[Tuple[torch.Tensor, torch.Tensor]] = None
    ) -> torch.Tensor:
        b, c, h, w, d = x.shape
        seq = rearrange(x, "b c h w d -> b (h w d) c")
        seq_norm = self.norm(seq)

        if film is not None:
            gamma, beta = film
            seq_norm = seq_norm * gamma.unsqueeze(1) + beta.unsqueeze(1)

        x_proj, gate = self.in_proj(seq_norm).chunk(2, dim=-1)
        x_proj = rearrange(x_proj, "b n c -> b c n")
        x_proj = self.conv(x_proj)
        x_proj = rearrange(x_proj, "b c n -> b n c")
        gated = self.act(x_proj) * torch.sigmoid(gate)
        out = self.out_proj(gated)
        out = self.dropout(out)
        out = out + seq
        out = rearrange(out, "b (h w d) c -> b c h w d", h=h, w=w, d=d)
        return out


class CrossConditionedMambaBridge(nn.Module):
    """
    Cross-layer FiLM modulation for a low-level Mamba block.

    High-level features generate FiLM parameters that modulate a low-level
    Mamba block, and an optional bidirectional path can push low-level context
    back to the high-level stream. Resampled high-level context is injected
    after the Mamba update to retain deformation cues across scales.
    """

    def __init__(
        self,
        low_dim: int,
        high_dim: int,
        reduction: int = 4,
        dropout: float = 0.0,
        bidirectional: bool = False,
    ):
        super().__init__()
        self.bidirectional = bidirectional
        self.film = FiLMParameterGenerator(high_dim, low_dim, reduction=reduction)
        self.mamba = SimpleMambaBlock(low_dim, dropout=dropout)
        self.high_adapter = nn.Conv3d(high_dim, low_dim, kernel_size=1)
        if self.bidirectional:
            self.low_to_high = nn.Conv3d(low_dim, high_dim, kernel_size=1)

    def forward(
        self, low_feat: torch.Tensor, high_feat: Optional[torch.Tensor] = None
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        film: Optional[Tuple[torch.Tensor, torch.Tensor]] = None
        high_resampled: Optional[torch.Tensor] = None

        if high_feat is not None:
            film = self.film(high_feat)
            high_resampled = F.interpolate(
                high_feat, size=low_feat.shape[2:], mode="trilinear", align_corners=False
            )

        out = self.mamba(low_feat, film)
        if high_resampled is not None:
            out = out + self.high_adapter(high_resampled)

        updated_high = high_feat
        if self.bidirectional and high_feat is not None:
            pooled_low = F.adaptive_avg_pool3d(out, high_feat.shape[2:])
            updated_high = high_feat + self.low_to_high(pooled_low)

        return out, updated_high



